In [1]:
t = ()

In [2]:
type(t)

tuple

In [3]:
t1 = (1,2,3,4,45,45.45, 45+7j, "Rahul", True)

In [4]:
type(t1)

tuple

Difference in tuple and list:
1. if we have to create a list we create it using '[]' and if we want create tuple we create it using '()'

In [10]:
l = [1,2,3,4]

In [11]:
type(l)

list

In [12]:
t1

(1, 2, 3, 4, 45, 45.45, (45+7j), 'Rahul', True)

once we create a tuple it creates an index inside it , through which we access tuple elements, starting from 0, 1, 2..etc.

In [8]:
t1[0]

1

In [9]:
t1[7]

'Rahul'

if some one ask can we get reverse of the tuple, so yes we can get it by applying '::-1'

In [ ]:
t1[::-1]

(True, 'Rahul', (45+7j), 45.45, 45, 4, 3, 2, 1)

if i do re-assignment then my final tuple wiil be reverse in order to its prior state

In [14]:
t1 = t1[::-1]

In [15]:
t1

(True, 'Rahul', (45+7j), 45.45, 45, 4, 3, 2, 1)

if question is asked that can i extract data from here ```(True, 'Rahul', (45+7j),``` to here , kind of slicing operation

In [18]:
t1[0:3]

(True, 'Rahul', (45+7j))

Yes, slicing is possible for chunk of information.

In [19]:
t1

(True, 'Rahul', (45+7j), 45.45, 45, 4, 3, 2, 1)

if question is asked that what are in-built functions available w.r.t tuple

In [ ]:
# t1.count()
# t1.index()

so yes we do have only two methods for tuple. namely `count()` and `index()`, more than that there no methods are available.

if we are not able to unerstand any functionality of a function then tap `shift + Tab` in jypyter notebook it will work, and python will give you complete doc string that will contain complete infromation about that function or can say method.

In [20]:
t1.count(4)

1

above function `count()` shows that how many times `4` is been appeared in give tuple

In [21]:
t1.count("abc")

0

as you can see it return `0`, means there is not such string in given tuple `t1`

In [24]:
t1

(True, 'Rahul', (45+7j), 45.45, 45, 4, 3, 2, 1)

`index()` function will give you index of very 1st occurences, it is going to give you.

In [25]:
t1.index(1)

0

as you can see we got `0` as indxe, but why we got `0` as index though we have reversed it and see it as last element of tuple.

In [26]:
t1

(True, 'Rahul', (45+7j), 45.45, 45, 4, 3, 2, 1)

In [22]:
t1.index(1)

0

*Answer:*

`(True, 'Rahul', (45+7j), 45.45, 45, 4, 3, 2, 1)'

in tuple out 1st element is of type `bool` which corresponds to `True` and system will store it as binary which is `1`, because of that `True` is recognized as `1` and we got index of `1` as `0`, `index()` is not providing index for last '1` in tuple.

In [27]:
t1.index('Rahul')

1

Let's check count if `1`

In [28]:
t1.count(1)

2

we got 2

Let's check count of `True`

In [29]:
t1.count(True)

2

again 2, strange isn't it, why this may have happened? we don't see two occurance of `1` or `True`

In [30]:
t1

(True, 'Rahul', (45+7j), 45.45, 45, 4, 3, 2, 1)

*Answer:* agains same answer as privious, system saves `True` as `1` anf `False` as `0`, so we got it saved in both froms,

`True` as `1` and `1` as `True`.

so for `t1.count(1)` it returns `2`

and for `t1.count(True)` it returns `2`

consider this truple t1 and list l, will try to understand mutability and immutability

In [31]:
t1

(True, 'Rahul', (45+7j), 45.45, 45, 4, 3, 2, 1)

In [32]:
l

[1, 2, 3, 4]

if we ask a quastion that can we extract a `(True,` from tuple, then Yes we can, simple indexing operation

In [33]:
t1[0]

True

Now, Question is can you assign something else on the place of `(True,` ?

In [34]:
t1[0] = 345

TypeError: 'tuple' object does not support item assignment

Let's perform same on list

In [35]:
l

[1, 2, 3, 4]

In [36]:
l[0] = 345

In [37]:
l

[345, 2, 3, 4]

here item assignment is different and concept of mutability and immutability is different, it is not item assignment.

assignment happens to a variable, here we are tring to change the content of a perticular place

list -> mutable
tuple -> immutabile

Tuple are basically follows Immutability concepts where it is not going to allow to change any element at a perticular index

In [38]:
t1

(True, 'Rahul', (45+7j), 45.45, 45, 4, 3, 2, 1)

now, question is can you iterate threought this tuple with the help of for loop?

-> Yes we can iterate through the tuple with for loop

In [39]:
for i in t1:
  print(i)

True
Rahul
(45+7j)
45.45
45
4
3
2
1

Question, addtion to upper question, can we print its data type simultaneously?

In [40]:
for i in t1:
  print(i, type(i))

True <class 'bool'>
Rahul <class 'str'>
(45+7j) <class 'complex'>
45.45 <class 'float'>
45 <class 'int'>
4 <class 'int'>
3 <class 'int'>
2 <class 'int'>
1 <class 'int'>

In [43]:
t2 = (1,2,3,3,4)

In [44]:
t2

(1, 2, 3, 3, 4)

In [45]:
t2 * 3

(1, 2, 3, 3, 4, 1, 2, 3, 3, 4, 1, 2, 3, 3, 4)

with above code it just duplicated the our prior tuple 3 times

- same applicable in terms of `list`
- same applicable in terms of `string`

Can we findout maximum out of the tuple ?

In [46]:
max(t2)

4

Can we findout minimum out of the tuple ?

In [47]:
min(t2)

1

Nested tuples

In [48]:
t1 = (1,2,32,4)
t2 = (4,5,6,7,8)

In [49]:
t3 = (t1, t2)

In [50]:
t3

((1, 2, 32, 4), (4, 5, 6, 7, 8))

we can keep tuple inside tuples

* we can also keep tuple inside list
* we can also keep list inside tuple

In [51]:
t4 = ((1,2,3,4,5), [1,2,3,4,5])

In [52]:
t4

((1, 2, 3, 4, 5), [1, 2, 3, 4, 5])

now, update is not possible and insert is not possible, but can we delete thye entire tuple?

In [53]:
del t4

In [54]:
t4

NameError: name 't4' is not defined

-> yes , we can see that deletion of entire tuple is possible.

In [55]:
t1

(1, 2, 32, 4)

we can get the numner of elements present inside the tuple

In [56]:
len(t1)

4

Question: can we know a perticular element is present inside a tuple or not?

In [58]:
"Rahul" in t1

False

No, "Rahul" string is not present in side my tuple `t1`

In [59]:
2 in t1

True

Yes, `2` is present in side the tuple `t1`